// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfaeneifadmdtebvxltq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmYWVuZWlmYWRtZHRlYnZ4bHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODA3MDgsImV4cCI6MjA2NTY1NjcwOH0.GcOvWJWQktQhaTUVoWtQ7qXPxVqtnBeAeIj9RhLscdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);